# config/routes.yaml

index:
    path: /
    controller: App\Controller\IndexController::index

list-all:
    path: /list/
    controller: App\Controller\ListController::all

list-category:
    path: /list/{id}
    controller: App\Controller\ListController::category

item:
    path: /item/{id}
    controller: App\Controller\ItemController::item

self:
    path: /self/
    controller: App\Controller\SelfController::self

user:
    path: /user/{id}
    controller: App\Controller\UserController::user

login:
    path: /login/
    controller: App\Controller\LoginController::login

logout:
    path: /logout/
    controller: App\Controller\LoginController::logout

cart:
    path: /cart/
    controller: App\Controller\CartController::cart

remove-to-cart:
    path: /removeToCart/{id}
    controller: App\Controller\CartController::removeToCart

add-to-cart:
    path: /addToCart/{id}
    controller: App\Controller\CartController::addToCart

command:
    path: /command/
    controller: App\Controller\CartController::command

command-final:
    path: /commandFinal/
    controller: App\Controller\CartController::commandFinal

api-login:
    path: /api/login
    controller: App\Controller\ApiController::login

api-fromages:
    path: /api/fromage
    controller: App\Controller\ApiController::fromages

api-fromage:
    path: /api/fromage/{id}
    controller: App\Controller\ApiController::fromage

api-types:
    path: /api/type
    controller: App\Controller\ApiController::types

api-type:
    path: /api/type/{id}
    controller: App\Controller\ApiController::type

api-laits:
    path: /api/lait
    controller: App\Controller\ApiController::laits

api-lait:
    path: /api/lait/{id}
    controller: App\Controller\ApiController::lait
